import { db } from "./index";
import { classesTable, origensTable, periciasTable } from "./schema/game";
import { count } from "drizzle-orm";

async function seed() {
  const [{ value: classCount }] = await db.select({ value: count() }).from(classesTable);
  if (Number(classCount) > 0) {
    console.log("==> Database already seeded, skipping.");
    process.exit(0);
  }

  console.log("==> Seeding database...");

  await db.insert(classesTable).values([
    {
      nome: "Combatente",
      descricao: "Especialista em combate físico e sobrevivência em situações extremas. Treinado para lidar com ameaças paranormais de frente.",
      pvInicial: 20, pvPorNivel: 5, peInicial: 3, pePorNivel: 2, sanInicial: 10, sanPorNivel: 3, periciasTreindasBase: 3,
    },
    {
      nome: "Especialista",
      descricao: "Profissional com habilidades técnicas avançadas. Usa inteligência e perícia para superar os desafios do paranormal.",
      pvInicial: 16, pvPorNivel: 4, peInicial: 4, pePorNivel: 2, sanInicial: 12, sanPorNivel: 4, periciasTreindasBase: 4,
    },
    {
      nome: "Ocultista",
      descricao: "Estudioso do sobrenatural com acesso a rituais e conhecimentos proibidos. Frágil mas poderoso.",
      pvInicial: 12, pvPorNivel: 3, peInicial: 6, pePorNivel: 3, sanInicial: 14, sanPorNivel: 5, periciasTreindasBase: 3,
    },
  ]);

  await db.insert(origensTable).values([
    // ── Livro Base ──────────────────────────────────────────────────────────
    { nome: "Acadêmico", fonte: "Livro Base", descricao: "Você trabalhou em uma universidade, instituto de pesquisa ou museu. Seu trabalho envolvia pesquisa, ensino ou curadoria de conhecimento. Em algum momento, suas pesquisas esbarraram no paranormal.", periciasConcedidas: ["Atualidades", "Ciências"], poderConcedido: "Estudioso", poderDescricao: "Você recebe +2 em testes de Atualidades e Ciências. Além disso, uma vez por cena, pode gastar 1 PE para fazer um teste de Atualidades ou Ciências no lugar de qualquer outra perícia de Intelecto." },
    { nome: "Agente de Saúde", fonte: "Livro Base", descricao: "Você trabalhou na área da saúde, seja como médico, enfermeiro, paramédico ou técnico. Seu contato com o sofrimento humano e, eventualmente, com casos inexplicáveis, o levou à Ordem.", periciasConcedidas: ["Medicina", "Vontade"], poderConcedido: "Socorrista", poderDescricao: "Você pode usar Medicina para estabilizar personagens sem um kit médico, com DT 15. Além disso, quando usa um kit médico, você pode gastar 2 PE para curar 1d6+INT PV adicionais." },
    { nome: "Amnésico", fonte: "Livro Base", descricao: "Você não se lembra de quem era antes. Talvez tenha sido um experimento, uma vítima de ritual ou simplesmente alguém que viu algo que não deveria. Sua vida começa agora, na Ordem.", periciasConcedidas: ["Reflexos", "Vontade"], poderConcedido: "Memória Fragmentada", poderDescricao: "Escolha duas perícias quaisquer. Você é treinado nelas (memórias de sua vida anterior). Além disso, uma vez por missão, pode 'lembrar' de algo relevante para a cena atual, a critério do mestre." },
    { nome: "Artista", fonte: "Livro Base", descricao: "Você era um ator, músico, escritor, pintor ou qualquer outro tipo de artista. Sua sensibilidade e criatividade o tornaram mais perceptivo ao paranormal.", periciasConcedidas: ["Artes", "Enganação"], poderConcedido: "Inspiração", poderDescricao: "Uma vez por cena, você pode gastar 2 PE para conceder +2 em um teste de perícia a um aliado em alcance médio." },
    { nome: "Chef", fonte: "Livro Base", descricao: "Você era um cozinheiro profissional, seja em um restaurante sofisticado ou em uma barraca de rua. Sua habilidade com ingredientes e sua criatividade na cozinha o tornaram um membro valioso da Ordem.", periciasConcedidas: ["Profissão (cozinheiro)", "Vontade"], poderConcedido: "Refeição Revigorante", poderDescricao: "Durante um interlúdio, você pode preparar uma refeição especial. Todos que a consumirem recuperam 1d6+PRE PV adicionais durante o descanso." },
    { nome: "Combatente", fonte: "Livro Base", descricao: "Você tem experiência em combate, seja como lutador de artes marciais, praticante de esportes de contato ou simplesmente alguém que cresceu em um ambiente violento.", periciasConcedidas: ["Atletismo", "Luta"], poderConcedido: "Durão", poderDescricao: "Você recebe +2 PV para cada NEX que possui. Além disso, quando fica com 0 PV, pode gastar 2 PE para ficar com 1 PV em vez de cair inconsciente." },
    { nome: "Criminoso", fonte: "Livro Base", descricao: "Você viveu à margem da lei, seja como ladrão, hacker, traficante ou outro tipo de criminoso. Suas habilidades ilícitas provaram ser surpreendentemente úteis na Ordem.", periciasConcedidas: ["Crime", "Furtividade"], poderConcedido: "Vida no Crime", poderDescricao: "Você recebe +2 em testes de Crime e Furtividade. Além disso, uma vez por cena, pode gastar 2 PE para substituir um teste de perícia qualquer por um teste de Crime." },
    { nome: "Detetive", fonte: "Livro Base", descricao: "Você trabalhou como detetive particular ou investigador. Sua habilidade em encontrar pistas e interrogar suspeitos o tornou um ativo valioso para a Ordem.", periciasConcedidas: ["Investigação", "Percepção"], poderConcedido: "Faro Investigativo", poderDescricao: "Você recebe +2 em testes de Investigação e Percepção. Além disso, quando examina uma cena de crime ou local suspeito, pode gastar 2 PE para fazer um teste de Investigação e descobrir uma pista adicional." },
    { nome: "Esportista", fonte: "Livro Base", descricao: "Você foi um atleta profissional ou amador de alto nível. Seu corpo treinado e sua mentalidade competitiva o tornaram um agente eficaz.", periciasConcedidas: ["Atletismo", "Reflexos"], poderConcedido: "Atleta", poderDescricao: "Você recebe +2 em testes de Atletismo e Reflexos. Além disso, seu deslocamento aumenta em 3 metros." },
    { nome: "Herdeiro", fonte: "Livro Base", descricao: "Você nasceu em uma família rica e influente. Seja por herança, casamento ou golpe de sorte, você tem acesso a recursos que a maioria das pessoas jamais terá.", periciasConcedidas: ["Diplomacia", "Intuição"], poderConcedido: "Recursos Familiares", poderDescricao: "Você recebe +2 em testes de Diplomacia. Além disso, uma vez por missão, pode gastar 5 PE para adquirir um item de Categoria I ou II sem custo." },
    { nome: "Jornalista", fonte: "Livro Base", descricao: "Você trabalhou como repórter, fotógrafo jornalístico ou editor. Sua curiosidade insaciável e sua habilidade em encontrar a verdade o levaram a investigar casos paranormais.", periciasConcedidas: ["Atualidades", "Investigação"], poderConcedido: "Fontes Confiáveis", poderDescricao: "Você recebe +2 em testes de Investigação. Além disso, uma vez por missão, pode contatar uma fonte e obter informações relevantes sobre o caso atual, a critério do mestre." },
    { nome: "Magnata", fonte: "Livro Base", descricao: "Você possui muito dinheiro ou patrimônio. Pode ser o herdeiro de uma família antiga ligada ao oculto, ter criado e vendido uma empresa e decidido usar sua riqueza para uma causa maior, ou ter ganho uma loteria após inadvertidamente escolher números amaldiçoados que formavam um ritual.", periciasConcedidas: ["Diplomacia", "Pilotagem"], poderConcedido: "Patrocinador da Ordem", poderDescricao: "Seu limite de crédito é sempre considerado um acima do atual." },
    { nome: "Mercenário", fonte: "Livro Base", descricao: "Você é um soldado de aluguel, que trabalha sozinho ou como parte de alguma organização que vende serviços militares. Escoltas e assassinatos fizeram parte de sua rotina por tempo o suficiente para você se envolver em alguma situação com o paranormal.", periciasConcedidas: ["Iniciativa", "Intimidação"], poderConcedido: "Posição de Combate", poderDescricao: "No primeiro turno de cada cena de ação, você pode gastar 2 PE para receber uma ação de movimento adicional." },
    { nome: "Militar", fonte: "Livro Base", descricao: "Você serviu em uma força militar, como o exército ou a marinha. Passou muito tempo treinando com armas de fogo, até se tornar um perito no uso delas. Acostumado a obedecer ordens e partir em missões, está em casa na Ordo Realitas.", periciasConcedidas: ["Pontaria", "Tática"], poderConcedido: "Para Bellum", poderDescricao: "Você recebe +2 em rolagens de dano com armas de fogo." },
    { nome: "Operário", fonte: "Livro Base", descricao: "Pedreiro, industriário, operador de máquinas em uma fábrica… Você passou uma parte de sua vida em um emprego braçal, desempenhando atividades práticas que lhe deram uma visão pragmática do mundo.", periciasConcedidas: ["Fortitude", "Profissão"], poderConcedido: "Ferramenta de Trabalho", poderDescricao: "Escolha uma arma simples ou tática que, a critério do mestre, poderia ser usada como ferramenta em sua profissão. Você sabe usar a arma escolhida e recebe +1 em testes de ataque, rolagens de dano e margem de ameaça com ela." },
    { nome: "Policial", fonte: "Livro Base", descricao: "Você fez parte de uma força de segurança pública, civil ou militar. Em alguma patrulha ou chamado se deparou com um caso paranormal e sobreviveu para contar a história.", periciasConcedidas: ["Percepção", "Pontaria"], poderConcedido: "Patrulha", poderDescricao: "Você recebe +2 em Defesa." },
    { nome: "Religioso", fonte: "Livro Base", descricao: "Você é devoto ou sacerdote de uma fé. Independentemente da religião que pratica, se dedica a auxiliar as pessoas com problemas espirituais. A partir disso, teve contato com o paranormal.", periciasConcedidas: ["Religião", "Vontade"], poderConcedido: "Acalentar", poderDescricao: "Você recebe +5 em testes de Religião para acalmar. Além disso, quando acalma uma pessoa, ela recebe um número de pontos de Sanidade igual a 1d6 + a sua Presença." },
    { nome: "Servidor Público", fonte: "Livro Base", descricao: "Você possuía carreira em um órgão do governo, lidando com burocracia e atendendo pessoas. Sua rotina foi quebrada quando você viu que o prefeito era um cultista ou que a câmara de vereadores se reunia à noite para realizar rituais.", periciasConcedidas: ["Intuição", "Vontade"], poderConcedido: "Espírito Cívico", poderDescricao: "Sempre que faz um teste para ajudar, você pode gastar 1 PE para aumentar o bônus concedido em +2." },
    { nome: "Teórico da Conspiração", fonte: "Livro Base", descricao: "A humanidade nunca pisou na lua. Reptilianos ocupam importantes cargos públicos. A Terra é plana... E secretamente governada pelos Illuminati. Você sabe isso tudo, pois investigou a fundo esses importantes assuntos.", periciasConcedidas: ["Investigação", "Ocultismo"], poderConcedido: "Eu Já Sabia", poderDescricao: "Você não se abala com entidades ou anomalias. Afinal, sempre soube que isso tudo existia. Você recebe resistência a dano mental igual ao seu Intelecto." },
    { nome: "T.I.", fonte: "Livro Base", descricao: "Programador, engenheiro de software ou simplesmente 'o cara da T.I.', você tem treinamento e experiência para lidar com sistemas informatizados. Seu talento (ou curiosidade exagerada) chamou a atenção da Ordem.", periciasConcedidas: ["Investigação", "Tecnologia"], poderConcedido: "Motor de Busca", poderDescricao: "A critério do Mestre, sempre que tiver acesso a internet, você pode gastar 2 PE para substituir um teste de perícia qualquer por um teste de Tecnologia." },
    { nome: "Trabalhador Rural", fonte: "Livro Base", descricao: "Você trabalhava no campo ou em áreas isoladas, como fazendeiro, pescador, biólogo, veterinário... Você se acostumou com o convívio com a natureza e os animais e talvez tenha ouvido uma ou outra história de fantasmas ao redor da fogueira.", periciasConcedidas: ["Adestramento", "Sobrevivência"], poderConcedido: "Desbravador", poderDescricao: "Quando faz um teste de Adestramento ou Sobrevivência, você pode gastar 2 PE para receber +5 nesse teste. Além disso, você não sofre penalidade em deslocamento por terreno difícil." },
    { nome: "Trambiqueiro", fonte: "Livro Base", descricao: "Uma vida digna exige muito trabalho, então é melhor nem tentar. Você vivia de pequenos golpes, jogatina ilegal e falcatruas. Certo dia, enganou a pessoa errada; no dia seguinte, se viu servindo à Ordem.", periciasConcedidas: ["Crime", "Enganação"], poderConcedido: "Impostor", poderDescricao: "Uma vez por cena, você pode gastar 2 PE para substituir um teste de perícia qualquer por um teste de Enganação." },
    { nome: "Universitário", fonte: "Livro Base", descricao: "Você era aluno de uma faculdade. Em sua rotina de estudos, provas e festas, acabou descobrindo algo — talvez um livro amaldiçoado na antiga biblioteca do campus? Por seu achado, foi convocado pela Ordem.", periciasConcedidas: ["Atualidades", "Investigação"], poderConcedido: "Dedicação", poderDescricao: "Você recebe +1 PE, e mais 1 PE adicional a cada NEX ímpar (15%, 25%...). Além disso, seu limite de PE por turno aumenta em 1." },
    { nome: "Vítima", fonte: "Livro Base", descricao: "Em algum momento de sua vida — infância, juventude ou início da vida adulta — você encontrou o paranormal... E a experiência não foi nada boa. Você viu os espíritos dos mortos, foi atacado por uma entidade ou mesmo foi sequestrado para ser sacrificado em um ritual.", periciasConcedidas: ["Reflexos", "Vontade"], poderConcedido: "Cicatrizes Psicológicas", poderDescricao: "Você recebe +1 de Sanidade para cada 5% de NEX." },

    // ── Sobrevivendo ao Horror ───────────────────────────────────────────────
    { nome: "Amigo dos Animais", fonte: "Sobrevivendo ao Horror", criador: "Gabriela 'Louie' | Arsenal Paranormal", descricao: "Você desenvolveu uma conexão muito forte com outros seres: os animais. Seja por nunca ter se dado muito bem com humanos ou por preferir a companhia de um melhor amigo de quatro patas, você leva sua vida ao lado de um bichano e até mesmo aprende com a natureza perceptiva deles.", periciasConcedidas: ["Adestramento", "Percepção"], poderConcedido: "Companheiro Animal", poderDescricao: "Você consegue entender as intenções e sentimentos de animais, e pode usar Adestramento para mudar a atitude deles. Além disso, você possui um melhor amigo, um animal que cresceu com você. Ele conta como um aliado que fornece +2 em uma perícia a sua escolha." },
    { nome: "Astronauta", fonte: "Sobrevivendo ao Horror", descricao: "Outrora limitada a membros de algumas agências espaciais estatais, a profissão de explorador espacial se tornou mais acessível. Como um astronauta, você se acostumou à pressão de ser responsável pela vida de seus colegas e por experimentos de milhões de reais. E foi na escuridão do espaço que você descobriu que não estamos sozinhos.", periciasConcedidas: ["Ciências", "Fortitude"], poderConcedido: "Acostumado ao Extremo", poderDescricao: "Quando sofre dano de fogo, de frio ou mental, você pode gastar 1 PE para reduzir esse dano em 5. A cada vez que usa esta habilidade novamente na mesma cena, seu custo aumenta em +1 PE." },
    { nome: "Chef do Outro Lado", fonte: "Sobrevivendo ao Horror", criador: "Julie Sathler | Ateliê Secreto", descricao: "Você nunca foi muito bom na culinária convencional. Depois de sobreviver ao paranormal, entretanto, descobriu um talento que é considerado um grande tabu até mesmo pelos ocultistas mais experientes: cozinhar e ingerir entidades do Outro Lado.", periciasConcedidas: ["Ocultismo", "Profissão (cozinheiro)"], poderConcedido: "Fome do Outro Lado", poderDescricao: "Você pode usar partes de criaturas do Outro Lado como ingredientes culinários. Pode preparar um prato especial durante um interlúdio; se passar no teste de Profissão (cozinheiro) DT 15+O, o prato fornece RD 10 contra o tipo de dano do elemento da criatura." },
    { nome: "Colegial", fonte: "Sobrevivendo ao Horror", descricao: "Você era um aluno do colegial e tinha uma rotina baseada nos estudos, nas amizades e nos dramas típicos de alguém da sua idade, até que um encontro com o paranormal mudou sua vida.", periciasConcedidas: ["Atualidades", "Tecnologia"], poderConcedido: "Poder da Amizade", poderDescricao: "Escolha um personagem para ser seu melhor amigo. Se estiver em alcance médio dele e puderem trocar olhares, você recebe +2 em todos os testes de perícia." },
    { nome: "Cosplayer", fonte: "Sobrevivendo ao Horror", criador: "Rafael 'Damnu' e Victor Moda | Toca dos Monstros", descricao: "Você é apaixonado pela arte do cosplay e dedicou sua vida a criar a melhor fantasia possível. Confrontado com o paranormal, você colocou sua arte, e sua resiliência, a serviço da Ordem.", periciasConcedidas: ["Artes", "Vontade"], poderConcedido: "Não É Fantasia, É Cosplay!", poderDescricao: "Você pode fazer testes de disfarce usando Artes em vez de Enganação. Além disso, ao fazer um teste de perícia, se estiver usando um cosplay que tem relação com ele, você recebe +2." },
    { nome: "Diplomata", fonte: "Sobrevivendo ao Horror", descricao: "Você atuava em uma área onde as habilidades sociais e políticas eram ferramentas indispensáveis. Talvez fosse representante comercial de uma empresa, membro de um partido político ou embaixador do governo.", periciasConcedidas: ["Atualidades", "Diplomacia"], poderConcedido: "Conexões", poderDescricao: "Você recebe +2 em Diplomacia. Além disso, se puder contatar um NPC capaz de lhe auxiliar, você pode gastar 10 minutos e 2 PE para substituir um teste de uma perícia relacionada ao conhecimento desse NPC por um teste de Diplomacia." },
    { nome: "Explorador", fonte: "Sobrevivendo ao Horror", criador: "Guilherme 'Guirassol' e João Vitor 'Vapor' | Arquivo do Medo", descricao: "Você é uma pessoa que se interessa muito por história ou geografia, frequentemente embarcando em trilhas e explorações para enriquecer seus estudos. Suas aventuras tornaram seu corpo mais resistente e capaz de se manter firme mesmo nas situações mais adversas.", periciasConcedidas: ["Fortitude", "Sobrevivência"], poderConcedido: "Manual do Sobrevivente", poderDescricao: "Ao fazer um teste para resistir a armadilhas, clima, doenças, fome, sede, fumaça, sono, sufocamento ou veneno, incluindo de fontes paranormais, você pode gastar 2 PE para receber +5 nesse teste." },
    { nome: "Experimento", fonte: "Sobrevivendo ao Horror", descricao: "Você foi uma cobaia em um experimento físico. Pode ter sido um voluntário em um procedimento experimental legítimo, ou submetido a experimentos científicos ou paranormais contra sua vontade.", periciasConcedidas: ["Atletismo", "Fortitude"], poderConcedido: "Mutação", poderDescricao: "Você recebe resistência a dano 2 e +2 em uma perícia à sua escolha que seja originalmente baseada em Força, Agilidade ou Vigor. Entretanto, sofre penalidade em Diplomacia." },
    { nome: "Fanático por Criaturas", fonte: "Sobrevivendo ao Horror", criador: "Everson 'Akkiel' e Yasmim Furtado | Grimório Paranormal", descricao: "Você sempre foi obcecado pelo sobrenatural. Desde que pode se lembrar, a ideia de encontrar uma criatura o fascina tanto quanto o assusta. Essa faísca fez você se tornar um 'caçador de monstros'.", periciasConcedidas: ["Investigação", "Ocultismo"], poderConcedido: "Conhecimento Oculto", poderDescricao: "Você pode fazer testes de Ocultismo para identificar criatura a partir de informações como uma imagem, rastros, indícios de sua presença ou outras pistas. Se passar, você descobre as características da criatura." },
    { nome: "Fotógrafo", fonte: "Sobrevivendo ao Horror", descricao: "Você é um artista visual que usa câmeras para capturar momentos e transmitir histórias através de imagens estáticas. Costumeiramente movido pela paixão de observar o mundo ao seu redor.", periciasConcedidas: ["Artes", "Percepção"], poderConcedido: "Através da Lente", poderDescricao: "Quando faz um teste de Investigação ou de Percepção para adquirir pistas olhando através de uma câmera ou analisando fotos, você pode gastar 2 PE para receber +5 nesse teste." },
    { nome: "Inventor Paranormal", fonte: "Sobrevivendo ao Horror", criador: "Bruno Sargi | C.R.I.S.", descricao: "A curiosidade e a criatividade fizeram de você uma pessoa que busca constantemente desafiar limites e criar soluções inovadoras, sendo mais de uma vez intitulado como um 'cientista louco'.", periciasConcedidas: ["Profissão (engenheiro)", "Vontade"], poderConcedido: "Invenção Paranormal", poderDescricao: "Escolha um ritual de 1º círculo. Você possui um invento paranormal, um item de categoria 0 que ocupa 1 espaço e que permite executar o efeito do ritual escolhido. Para ativar o invento, gasta uma ação padrão e faz um teste de Profissão (engenheiro) com DT 15 +5 para cada ativação na mesma missão." },
    { nome: "Jovem Místico", fonte: "Sobrevivendo ao Horror", criador: "Ramon 'PlayRay' e João 'Portill' | A Passagem", descricao: "Você possui uma profunda conexão com sua espiritualidade, suas crenças ou o próprio universo. Essa conexão faz com que você veja o mundo e viva sua vida de forma diferente e peculiar.", periciasConcedidas: ["Ocultismo", "Religião"], poderConcedido: "A Culpa é das Estrelas", poderDescricao: "Escolha um número da sorte entre 1 e 6. No início de cada cena, você pode gastar 1 PE e rolar 1d6. Se o resultado for seu número da sorte, você recebe +2 em testes de perícia até o fim da cena." },
    { nome: "Legista do Turno da Noite", fonte: "Sobrevivendo ao Horror", criador: "Ivo 'Eddu' e Ana Beatriz 'Bix' | Arquivos Confidenciais", descricao: "Em um trabalho como o seu, é de se esperar que você já tenha visto muita coisa. No entanto, quando o sol se põe, seus colegas vão embora e a luz artificial deixa cantos sombrios do necrotério, talvez você veja mais do que gostaria.", periciasConcedidas: ["Ciências", "Medicina"], poderConcedido: "Luto Habitual", poderDescricao: "Você sofre apenas a metade do dano mental por presenciar uma cena relacionada à rotina de um legista. Além disso, quando faz um teste de Medicina para primeiros socorros ou necropsia, você pode gastar 2 PE para receber +5 nesse teste." },
    { nome: "Mateiro", fonte: "Sobrevivendo ao Horror", descricao: "Você conhece áreas rurais e selvagens. Você pode ser um guia florestal, um biólogo de campo ou simplesmente um entusiasta da vida selvagem. Qualquer que seja sua relação com a natureza, ela foi sua porta para o contato com o Outro Lado.", periciasConcedidas: ["Percepção", "Sobrevivência"], poderConcedido: "Mapa Celeste", poderDescricao: "Desde que possa ver o céu, você sempre sabe as direções dos pontos cardeais e consegue chegar sem se perder em qualquer lugar que já tenha visitado ao menos uma vez. Quando faz um teste de Sobrevivência, você pode gastar 2 PE para rolar o teste novamente e escolher o melhor entre os dois resultados." },
    { nome: "Mergulhador", fonte: "Sobrevivendo ao Horror", descricao: "Seja por profissão ou por hobby, você é um aventureiro subaquático que explora os mistérios e maravilhas do mundo submerso. Trajando seu equipamento de mergulho, você consegue se aventurar a grandes profundidades.", periciasConcedidas: ["Atletismo", "Fortitude"], poderConcedido: "Fôlego de Nadador", poderDescricao: "Você recebe +5 PV e pode prender a respiração por um número de rodadas igual ao dobro do seu Vigor. Além disso, quando passa em um teste de Atletismo para natação, você avança seu deslocamento normal." },
    { nome: "Motorista", fonte: "Sobrevivendo ao Horror", descricao: "Você é um caminhoneiro, motorista de aplicativo, motoboy, piloto de corrida, motorista de ambulância ou qualquer outro tipo de condutor profissional. Você levava a vida transportando cargas ou passageiros.", periciasConcedidas: ["Pilotagem", "Reflexos"], poderConcedido: "Mãos no Volante", poderDescricao: "Você não sofre penalidades em testes de ataque por estar em um veículo em movimento e, sempre que estiver pilotando e tiver que fazer um teste de Pilotagem ou resistência, pode gastar 2 PE para receber +5 nesse teste." },
    { nome: "Nerd Entusiasta", fonte: "Sobrevivendo ao Horror", criador: "Daniel Dill e Lukas Castanho | Remate Paranormal", descricao: "Você dedicou muito do seu tempo aprendendo sobre videogames, RPGs de mesa, ficção científica ou qualquer outro assunto considerado 'nerd'. Sua obsessão em pesquisar fundo seus assuntos de interesse chamou a atenção de organizações paranormais.", periciasConcedidas: ["Ciências", "Tecnologia"], poderConcedido: "O Inteligentão", poderDescricao: "O bônus que você recebe ao utilizar a ação de interlúdio ler aumenta em +1 dado (de +1d6 para +2d6)." },
    { nome: "Profetizado", fonte: "Sobrevivendo ao Horror", descricao: "Como qualquer pessoa, você vai morrer. Entretanto, diferente delas, você sabe como isso vai acontecer. De algum jeito, seja por pesadelos, pensamentos intrusivos ou até visões inesperadas, você tem uma premonição clara de como serão seus últimos momentos de vida.", periciasConcedidas: ["Vontade", "Uma à sua escolha relacionada à premonição"], poderConcedido: "Luta ou Fuga", poderDescricao: "Conhecer os sinais de sua morte o deixa mais confiante, principalmente quando eles não estão presentes. Você recebe +2 em Vontade. Quando surge uma referência a sua premonição, você recebe +2 PE temporários que duram até o fim da cena." },
    { nome: "Psicólogo", fonte: "Sobrevivendo ao Horror", criador: "Luiz Giovane e Matheus Santana | Missões Ordem", descricao: "Você se especializou no estudo e tratamento das questões mentais do ser humano. Em sua prática profissional, você teve contato com o paranormal e descobriu que algumas aflições mentais possuem origens sombrias e perigosas.", periciasConcedidas: ["Intuição", "Profissão (psicólogo)"], poderConcedido: "Terapia", poderDescricao: "Você pode usar Profissão (psicólogo) como Diplomacia. Além disso, uma vez por rodada, quando você ou um aliado em alcance curto falha em um teste de resistência contra um efeito que causa dano mental, você pode gastar 2 PE para fazer um teste de Profissão (psicólogo) e usar o resultado no lugar." },
    { nome: "Repórter Investigativo", fonte: "Sobrevivendo ao Horror", descricao: "Você está sempre em busca de histórias significativas, investigando eventos, entrevistando fontes e analisando dados para descobrir a verdade por trás dos acontecimentos.", periciasConcedidas: ["Atualidades", "Investigação"], poderConcedido: "Encontrar a Verdade", poderDescricao: "Você pode usar Investigação no lugar de Diplomacia ao fazer testes para persuadir e mudar atitude e, quando faz um teste de Investigação, pode gastar 2 PE para receber +5 nesse teste." },
  ]);

  await db.insert(periciasTable).values([
    { nome: "Acrobacia", atributoBase: "Agilidade", somenteTrainada: false },
    { nome: "Adestramento", atributoBase: "Presença", somenteTrainada: false },
    { nome: "Artes", atributoBase: "Presença", somenteTrainada: true },
    { nome: "Armas de Fogo", atributoBase: "Agilidade", somenteTrainada: true },
    { nome: "Atletismo", atributoBase: "Vigor", somenteTrainada: false },
    { nome: "Atualidades", atributoBase: "Intelecto", somenteTrainada: false },
    { nome: "Ciências", atributoBase: "Intelecto", somenteTrainada: true },
    { nome: "Crime", atributoBase: "Agilidade", somenteTrainada: true },
    { nome: "Diplomacia", atributoBase: "Presença", somenteTrainada: false },
    { nome: "Enganação", atributoBase: "Presença", somenteTrainada: false },
    { nome: "Fortitude", atributoBase: "Vigor", somenteTrainada: false },
    { nome: "Furtividade", atributoBase: "Agilidade", somenteTrainada: false },
    { nome: "Iniciativa", atributoBase: "Agilidade", somenteTrainada: false },
    { nome: "Intimidação", atributoBase: "Presença", somenteTrainada: false },
    { nome: "Intuição", atributoBase: "Presença", somenteTrainada: false },
    { nome: "Investigação", atributoBase: "Intelecto", somenteTrainada: false },
    { nome: "Luta", atributoBase: "Força", somenteTrainada: false },
    { nome: "Medicina", atributoBase: "Intelecto", somenteTrainada: true },
    { nome: "Ocultismo", atributoBase: "Intelecto", somenteTrainada: true },
    { nome: "Percepção", atributoBase: "Intelecto", somenteTrainada: false },
    { nome: "Persuasão", atributoBase: "Presença", somenteTrainada: false },
    { nome: "Pilotagem", atributoBase: "Agilidade", somenteTrainada: true },
    { nome: "Pontaria", atributoBase: "Agilidade", somenteTrainada: false },
    { nome: "Profissão", atributoBase: "Intelecto", somenteTrainada: true },
    { nome: "Reflexos", atributoBase: "Agilidade", somenteTrainada: false },
    { nome: "Religião", atributoBase: "Presença", somenteTrainada: true },
    { nome: "Resiliência", atributoBase: "Vigor", somenteTrainada: false },
    { nome: "Sobrevivência", atributoBase: "Intelecto", somenteTrainada: false },
    { nome: "Tática", atributoBase: "Intelecto", somenteTrainada: true },
    { nome: "Tecnologia", atributoBase: "Intelecto", somenteTrainada: true },
    { nome: "Vontade", atributoBase: "Presença", somenteTrainada: false },
  ]);

  console.log("==> Seed complete.");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
